[package]
name = "SkyDecode"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
metar = "0.1"
tabled = "0.16"
clap = { version = "4", features = ["derive"] }
colored = "3"
indicatif = "0.17"
